# Generated by Django 2.2.9 on 2021-10-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='senha',
            field=models.CharField(default='', max_length=255),
        ),
    ]
