# Generated by Django 2.2.9 on 2021-10-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_administrator_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='telefone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
